Ways ← /+ > : × ⇌ . ⇡ +1 ?
. &fras $ input.txt
ParseBy! ← ⊜(^1) ≠ @\n .

# Part 1
ParseBy!(♭ ⋕ regex "\\d+")
: /× /∵Ways

# Part 2
ParseBy!(□ regex "\\d+")
∵(⋕ ⊐/⊂ ♭)
Ways °⊟

# Ways = reduce add > flip multiply reverse duplicate range +1 ?
# . &fras $ input.txt
# ParseBy! = partition (^1) != @\n duplicate

# # Part 1
# ParseBy!(deshape parse regex "\\d+")
# flip reduce * reduce each Ways

# # Part 2
# ParseBy!(box regex "\\d+")
# each (parse unpack reduce join deshape)
# Ways un couple
